config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  get '/auctions/index2', to: 'auctions#index2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :auctions do
    resources :bids, only: [:create, :destroy]
    resources :publishings, only: [:create]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :bids, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, uniqueness: { case_sensitive: false}
  # Doesn't this just check that the reserve_price == reserve_price?
  # ie. isn't it always true?
  validates :reserve_price, numericality: { greater_than_or_equal_to: :default_auction_price }

  def default_auction_price
    self.reserve_price ||= 1
  end

  before_save :default_values

  def default_values
    self.current_price ||= self.reserve_price
  end

  def set_current_price
    self.reserve_price
  end

  include AASM
  aasm do
    state :draft, initial: true
    state :published, :reserve_met, :won, :canceled, :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :cancel do
      transitions from: [:published, :draft, :reserve_met, :reserve_not_met], to: :canceled
    end

    event :reserve do
      transitions from: [:published], to: :reserve_met
    end

    event :unreserve do
      transitions from: :reserve_met, to: :reserve_not_met
    end

    event :win do
      transitions from: [:reserve_met], to: :won
    end

  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user

  validates :bid, numericality: { greater_than: :current_bid }

  def current_bid
    self.auction.current_price
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :auctions, dependent: :nullify
  has_many :bids, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    format: VALID_EMAIL_REGEX
  before_validation :downcase_email

  def full_name
    "#{first_name} #{last_name}"
  end

  def downcase_email
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please sign in!'
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :find_auction, only: [:show, :edit, :update, :destroy]

  def index
    @auctions = Auction.all
  end

  # why?
  def index2
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user
    if @auction.save
      flash[:notice] = "Auction created"
      redirect_to auctions_path
    else
      flash.now[:alert] = "Please fix errors"
      render :new
    end
  end

  def show
    # @auction = Auction.find params[:id]
    @bid = Bid.new
    @bids = @auction.bids.order(created_at: :desc)
  end

  def edit
    # @auction = Auction.find params[:id]
  end

  def update
    # @auction = Auction.find params[:id]

    if @auction.update(auction_params)
      redirect_to auctions_path, notice: "Successfully Updated"
    else
      flash.now[:alert] = 'Please fix errors'
      render :edit
    end

  end

  def destroy
    # @auction = Auction.find params[:id]
    @auction.destroy
    redirect_to auctions_path, alert: "Auction Deleted"
  end


  private

  def auction_params
    params.require(:auction).permit([:title, :details, :ends_on, :reserve_price])
  end

  def find_auction
    @auction = Auction.find params[:id]
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_bid, only: [:destroy]

  def create
    @auction = Auction.find params[:auction_id]
    @bid = Bid.new bid_params
    @bid.auction = @auction
    @bid.user = current_user
    # This belongs in a transaction. What if 
    # the auction fails to update?
    # Also, consider using a service object
    if @bid.save
      @auction.update_attributes(current_price: @bid.bid)
      redirect_to auction_path(@auction), notice: "Bid Created"
    else
      render 'auctions/show'
    end
  end

  def destroy
    @auction = @bid.auction # or
    # @auction = Auction.find params[:auction_id]
    @bid.destroy
    redirect_to auction_path(@auction), notice: 'Bid Deleted!'
  end


  private

  def find_bid
    @bid = Bid.find(params[:id])
  end

  def bid_params
    params.require(:bid).permit(:bid)
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController

  def create
    auction = Auction.find params[:auction_id]
    if auction.publish!
      redirect_to auction, notice: 'Auction published!'
    else
      redirect_to auction, notice: 'Auction not published!'
    end

    # if auction.cancel!
    #   redirect_to auction, notice: 'Auction cancelled!'
    # else
    #   redirect_to auction, notice: 'Auction not cancelled!'
    # end
    #
    # if auction.reserve!
    #   redirect_to auction, notice: 'Auction reserved!'
    # else
    #   redirect_to auction, notice: 'Auction not reserved!'
    # end
    #
    # if auction.win!
    #   redirect_to auction, notice: 'Auction won!'
    # else
    #   redirect_to auction, notice: 'Auction not won!'
    # end
    #
    # if auction.unreserve!
    #   redirect_to auction, notice: 'Auction unreserved!'
    # else
    #   redirect_to auction, notice: 'Auction could not unreserved!'
    # end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to auctions_path, notice: "#{@user.first_name} succesfully logged in"
    else
      flash.now[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to auctions_path, notice: "Signed Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to auctions_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_form.html.erb
<%= @auction.errors.full_messages.join(', ') %>
  <%= form_for @auction do |f|  %>
    <div class="row">
      <div class="col-lg-1">
        <%= f.label :title %>
      </div>
      <div class="col-lg-1">
        <%= f.text_field :title %>
      </div>
    </div> <br />

    <div class="row">
      <div class="col-lg-1">
        <%= f.label :details %>
      </div>
      <div class="col-lg-1">
        <%= f.text_area :details%>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1">
        <%= f.label :ends_on, "Ends On" %>
      </div>
      <div class="col-lg-1">
        <%= f.text_field :ends_on, data:{ provide:'datepicker' }, placeholder: "    /   / ", size: '8px' %>
        <script type="text/javascript">
          $(document).ready(function(){
            $('.datepicker').datepicker();
          });
        </script>
        <!-- <label for='end_date'><i class="fa fa-calendar" aria-hidden="true"></i></label> -->
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1">
        <%= f.label :reserved_price %>
      </div>
      <div class="col-lg-1">
        <%= f.text_field :reserved_price, placeholder: 1 %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1">
      </div>
      <div class="col-lg-1">
        <%= f.submit 'Save' %>
      </div>
    </div>

  <% end %>

app/views/auctions/index.html.erb
<div class="container">
  <% @auctions.each do |auction| %>
    <p><strong><%= link_to auction.title, auction_path(auction) %></strong></p>
  <% end %>
</div>

app/views/auctions/index2.html.erb
<div class="container">
  <% @auctions.each do |auction| %>
    <% if auction.bids.present? %>
      <p><strong><%= link_to auction.title, auction_path(auction) %></strong></p>
    <% end %>
  <% end %>
</div>

app/views/auctions/new.html.erb
<%= render 'form' %>

app/views/auctions/show.html.erb
<div class="container">

  <div class="row">
    <div class="col--lg-1 pull-left" style="margin-left: 10px">
      <h4><%= @auction.title %></h4>
    </div>
    <div class="col--lg-1 pull-right" style="margin-right: 200px">
      <p>Current Price: <%= @auction.current_price || number_to_currency(@auction.bids.order(bid: :DESC).first&.bid) %></p>
    </div>
  </div>

  <div class="row">
    <div class="col--lg-1 pull-left" style="margin-left: 10px">
      <p><%= @auction.details %></p>
    </div>


    <% if user_signed_in? && current_user == @auction.user %>
    <%= link_to 'Edit', edit_auction_path(@auction) %>

    | <%= link_to 'Delete', auction_path(@auction),
                              method: :delete,
                              data: {confirm: 'Are you sure?'} %>
    <% end %>

      <% if user_signed_in? && current_user != @auction.user %>
        <%= @bid.errors.full_messages.join(', ') %>
      <%= render'bids/form', bid: @bid %>
      <% end %>

    <div id="bids">
      <%= render 'bids/bids', bids: @bids %>
    </div>
  </div>


<% if user_signed_in? && current_user == @auction.user %>
  <% if @auction.may_publish? %>
    <%= link_to 'Publish', auction_publishings_path(@auction),
                           method: :post,
                           data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

</div>

app/views/bids/_bids.html.erb
<% bids&.each do |bid|%>
<div class="container">
  <div class="row">
    <div class="col-lg-4 pull-right">
      <%= number_to_currency(bid.bid) %>  At: <%= bid.created_at %> By: <%= bid.user.full_name %>
      <!-- <#%= link_to "Delete", [@auction, bid],
      method: :delete,
      remote: :true,
      data: {confirm: 'Are you sure?'} %> -->
    </div>
  </div>
</div>
<% end %>

app/views/bids/_form.html.erb
<!-- <%= bid&.errors.full_messages %> -->
<%= form_for [@auction, bid]  do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-4 pull-right">
      <%= f.text_field :bid %>
      <%= f.submit "Bid" %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiddingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= link_to 'Auctions', auctions_path %>
      |
      <%= link_to 'Create Auction', new_auction_path %>

      <% if user_signed_in? %>
      Hello <%= current_user.first_name %>

      <%= link_to 'Sign Out', sessions_path, method: :delete  %>
      |
      <%= link_to 'Bidded Auctions', auctions_index2_path %>
      <% else %>
      |
      <%= link_to 'Sign In', new_session_path %>
      |
      <%= link_to 'Sign Up', new_user_path %>
      <% end %>
      <hr>


    <% if flash.any? %>
     <hr>
     <% if flash[:notice] %>
       <div class="flash-notice"><%= flash[:notice] %></div>
     <% elsif flash[:alert] %>
       <div class="flash-alert"><%= flash[:alert] %></div>
     <% end %>
     <hr>
   <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <%= @user.errors.full_messages.join(', ') %>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div>
      <%= f.label :email%>
      <%= f.email_field :email %>
    </div>

    <div>
      <%= f.label :password%>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit %>

    <% end %>